import { StudyPlan, StudyMaterial, StudyProgress, User, AssessmentResult } from "../models/index.mjs";

/**
 * Fetches all study plans from the database.
 */
export const getAllStudyPlans = async () => {
  return await StudyPlan.find().sort({ createdAt: -1 });
};

/**
 * Fetches all study materials from the database.
 */
export const getAllStudyMaterials = async () => {
  return await StudyMaterial.find().sort({ createdAt: -1 });
};

/**
 * Fetches a single study material by ID.
 */
export const getStudyMaterialById = async (id) => {
  return await StudyMaterial.findById(id);
};

/**
 * Gets or creates study progress for a user.
 */
export const getOrCreateStudyProgress = async (userId) => {
  let progress = await StudyProgress.findOne({ userId }).populate("studyMaterialId");
  if (!progress) {
    // Try to find a matching material by user stream
    const user = await User.findById(userId);
    const stream = user?.stream || "General";
    
    let material = await StudyMaterial.findOne({ subject: new RegExp(stream, "i") });
    if (!material) {
      material = await StudyMaterial.findOne({}); // Fallback to any material
    }

    if (material) {
      progress = await StudyProgress.create({
        userId,
        studyMaterialId: material._id,
      });
      progress = await progress.populate("studyMaterialId");
    }
  }
  return progress;
};

/**
 * Updates study progress.
 */
export const updateStudyProgress = async (userId, chapterIndex, topicIndex) => {
  const progress = await StudyProgress.findOne({ userId });
  if (!progress) return null;

  progress.currentChapterIndex = chapterIndex;
  progress.currentTopicIndex = topicIndex;
  progress.lastAccessedAt = new Date();
  
  // Logic for completion could be added here
  
  await progress.save();
  return progress;
};

/**
 * Marks a topic as completed and moves to the next one.
 */
export const completeCurrentTopic = async (userId) => {
  let progress = await StudyProgress.findOne({ userId }).populate("studyMaterialId");
  if (!progress || !progress.studyMaterialId) return null;

  const chapters = progress.studyMaterialId.chapters || [];
  const currentChapter = chapters[progress.currentChapterIndex];
  if (!currentChapter) return progress;

  const topics = currentChapter.topics || [];
  
  if (progress.currentTopicIndex < topics.length - 1) {
    // Next topic in same chapter
    progress.currentTopicIndex += 1;
  } else if (progress.currentChapterIndex < chapters.length - 1) {
    // Next chapter, first topic
    progress.currentChapterIndex += 1;
    progress.currentTopicIndex = 0;
  } else {
    // All done
    progress.isCompleted = true;
  }

  progress.lastAccessedAt = new Date();
  await progress.save();
  return progress;
};

/**
 * Normalizes assessment questions generated by AI.
 */
const normalizeAssessmentQuestions = (raw, limit = 10) => {
  if (!Array.isArray(raw)) return [];
  return raw
    .map((item, idx) => {
      const options = Array.isArray(item?.options)
        ? item.options.map((opt) => String(opt || "").trim()).filter(Boolean)
        : [];
      const question = String(item?.question || "").trim();
      if (!question || options.length < 2) return null;
      const correctAnswer = String(item?.correctAnswer || "").trim();
      return {
        id: String(item?.id || `q${idx + 1}`),
        question,
        options: options.slice(0, 4),
        correctAnswer: correctAnswer || options[0],
      };
    })
    .filter(Boolean)
    .slice(0, limit);
};

/**
 * Generates an assessment for a specific chapter index.
 */
export const generateChapterAssessment = async (userId, chapterIndex, { openai, openAiModel }) => {
  const progress = await getOrCreateStudyProgress(userId);
  if (!progress || !progress.studyMaterialId) throw new Error("No study material assigned.");

  const material = progress.studyMaterialId;
  const chapter = material.chapters[chapterIndex];
  if (!chapter) throw new Error(`Chapter at index ${chapterIndex} not found.`);

  // Combine topic content for context
  const context = chapter.topics
    .map((t) => `Topic: ${t.title}\nContent: ${t.content}`)
    .join("\n\n");

  if (!openai) throw new Error("AI service unavailable.");

  const completion = await openai.chat.completions.create({
    model: openAiModel || "gpt-4o-mini",
    temperature: 0.3,
    messages: [
      {
        role: "system",
        content: `Create 10 MCQ questions based on the following study chapter content. Return strict JSON: {"title":"...","questions":[{"id":"q1","question":"...","options":["...","...","...","..."],"correctAnswer":"..."}]}`,
      },
      {
        role: "user",
        content: `Chapter Title: ${chapter.chapterTitle}\n\nContent:\n${context}`,
      },
    ],
  });

  const raw = String(completion.choices?.[0]?.message?.content || "").trim();
  let parsed = {};
  try {
    parsed = JSON.parse(raw);
  } catch {
    const match = raw.match(/\{[\s\S]*\}/);
    parsed = match ? JSON.parse(match[0]) : {};
  }

  const questions = normalizeAssessmentQuestions(parsed?.questions, 10);
  return {
    title: String(parsed?.title || `Assessment: ${chapter.chapterTitle}`),
    questions,
  };
};

/**
 * Saves or updates assessment results.
 */
export const saveChapterAssessment = async (userId, chapterIndex, userAnswers) => {
  const progress = await getOrCreateStudyProgress(userId);
  if (!progress || !progress.studyMaterialId) throw new Error("No study material assigned.");

  const materialId = progress.studyMaterialId._id;
  
  // Calculate score
  let score = 0;
  const processedAnswers = [];
  
  // Note: Validation of correct answers should ideally be done against cached questions,
  // but since we generate them on the fly, we rely on the payload for this simplified version.
  // In a production app, questions should be stored before being sent to the client.
  for (const ans of userAnswers) {
    if (ans.isCorrect) score += 1;
    processedAnswers.push({
      questionId: ans.id,
      selectedOption: ans.selected,
      isCorrect: ans.isCorrect
    });
  }

  const existing = await AssessmentResult.findOne({ userId, studyMaterialId: materialId, chapterIndex });
  if (existing) {
    existing.score = score;
    existing.answers = processedAnswers;
    existing.attempts += 1;
    await existing.save();
    return existing;
  }

  const newResult = await AssessmentResult.create({
    userId,
    studyMaterialId: materialId,
    chapterIndex,
    score,
    totalQuestions: processedAnswers.length || 10,
    answers: processedAnswers,
    attempts: 1
  });

  return newResult;
};

/**
 * Retrieves assessment statuses for all chapters of the current material.
 */
export const getAssessmentStatuses = async (userId) => {
  const progress = await getOrCreateStudyProgress(userId);
  if (!progress || !progress.studyMaterialId) return [];

  const results = await AssessmentResult.find({ 
    userId, 
    studyMaterialId: progress.studyMaterialId._id 
  }).lean();

  return results.map(r => ({
    chapterIndex: r.chapterIndex,
    score: r.score,
    totalQuestions: r.totalQuestions,
    attempts: r.attempts,
    updatedAt: r.updatedAt
  }));
};
