const { onboardStudent, getFullProfile, getFullMarks, parseAndSaveStudyMaterial, parseAndSaveStudyPlan, assignPlanToStudent, getCurrentWeekProgress, updateTopicCompletion, getAllPlans, getAllMaterials, getStudentActivePlan } = require('../services/dataService');
const { asyncHandler } = require('../middlewares/errorMiddleware');

// @desc    Onboard student data (academic info)
// @route   POST /api/data/onboarding
// @access  Private
const saveStudentData = asyncHandler(async (req, res) => {
    const studentId = req.user.id; // From auth middleware
    const data = await onboardStudent(studentId, req.body);
    res.status(201).json({ success: true, data });
});

// @desc    Get full student profile (identity + academic info)
// @route   GET /api/data/profile
// @access  Private
const getProfile = asyncHandler(async (req, res) => {
    const studentId = req.user.id; // From auth middleware
    const profile = await getFullProfile(studentId);
    res.status(200).json({ success: true, data: profile });
});

// @desc Get only marks
// @route GET /api/data/marks
// @access Private
const getMarks = asyncHandler(async (req, res) => {
    const studentId = req.user.id;
    const marks = await getFullMarks(studentId);
    res.status(200).json({ success: true, data: marks });
});

// @desc Parse and save Study Material PDF
// @route POST /api/data/study-material
const parseStudyMaterial = asyncHandler(async (req, res) => {
    const subject = req.body.subject; 
    const file = req.file; // This is the file object generated by Multer!

    if(!file) {
        return res.status(400).json({ success: false, message: 'Please upload a PDF file' });
    }

    // We pass the buffer and originalname over to your service
    const material = await parseAndSaveStudyMaterial(file.buffer, file.originalname, subject);
    res.status(201).json({ success: true, data: material });
});

// @desc Parse and save Study Plan PDF
// @route POST /api/data/study-plan
const parseStudyPlan = asyncHandler(async (req, res) => {
    const planName = req.body.planName;
    const file = req.file;

    if(!file) {
        return res.status(400).json({ success: false, message: 'Please upload a PDF file' });
    }

    const plan = await parseAndSaveStudyPlan(file.buffer, file.originalname, planName);
    res.status(201).json({ success: true, data: plan });
});

// @desc Assign a study plan to a student
// @route POST /api/data/assign-plan
const assignPlan = asyncHandler(async (req, res) => {
    const { planId, startDate } = req.body;
    const studentId = req.user.id;
    const assignment = await assignPlanToStudent(studentId, planId, startDate);
    res.status(200).json({ success: true, data: assignment });
});

// @desc Get current week progress
// @route GET /api/data/current-week-progress
const getWeekProgress = asyncHandler(async (req, res) => {
    const studentId = req.user.id;
    const progress = await getCurrentWeekProgress(studentId);
    res.status(200).json({ success: true, data: progress });
});

// @desc Update topic completion (Internal use by Voice Agent)
// @route POST /api/data/internal/update-topic
const updateTopicInternal = asyncHandler(async (req, res) => {
    const { studentId, topicName, secret } = req.body;
    
    // Simple secret check for internal calls
    if (secret !== process.env.INTERNAL_KEY) {
        return res.status(403).json({ success: false, message: 'Forbidden' });
    }

    const assignment = await updateTopicCompletion(studentId, topicName);
    res.status(200).json({ success: true, data: assignment });
});

// @desc Get all study plans
// @route GET /api/data/study-plans
const getStudyPlans = asyncHandler(async (req, res) => {
    const plans = await getAllPlans();
    res.status(200).json({ success: true, data: plans });
});

// @desc Get all study materials
// @route GET /api/data/study-materials
const getStudyMaterials = asyncHandler(async (req, res) => {
    const materials = await getAllMaterials();
    res.status(200).json({ success: true, data: materials });
});

// @desc Get current student's active plan
// @route GET /api/data/student-plan
const getStudentActivePlanController = asyncHandler(async (req, res) => {
    const studentId = req.user.id;
    const plan = await getStudentActivePlan(studentId);
    res.status(200).json({ success: true, data: plan });
});

module.exports = {
    saveStudentData,
    getProfile,
    getMarks,
    parseStudyMaterial,
    parseStudyPlan,
    assignPlan,
    getWeekProgress,
    updateTopicInternal,
    getStudyPlans,
    getStudyMaterials,
    getStudentActivePlan: getStudentActivePlanController
}